# Generated by Django 2.2.20 on 2021-04-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_webhooks_shopify', '0006_add_webhook_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorder',
            name='action',
            field=models.CharField(choices=[('enroll', 'enroll'), ('unenroll', 'unenroll')], default='enroll', max_length=8),
            preserve_default=False,
        ),
    ]
