# Generated by Django 2.2.20 on 2021-04-13 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edx_webhooks_shopify', '0007_shopifyorder_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopifyorder',
            old_name='id',
            new_name='order_id',
        ),
        migrations.AlterField(
            model_name='shopifyorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edx_webhooks_shopify.ShopifyOrder', to_field='order_id'),
        ),
        # Temporary modification to ensure the new ID field is added
        migrations.AddField(
            model_name='shopifyorder',
            name='id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='order_id',
            field=models.BigIntegerField(editable=False),
        ),
    ]
