# Generated by Django 2.2.20 on 2021-04-13 06:30

from django.db import migrations, models
import django.db.models.deletion


def populate(apps, schema_editor):
   model = apps.get_model('edx_webhooks_woocommerce', 'woocommerceorder')
   for index, item in enumerate(model.objects.all(), start=1):
       item.id = index
       item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('edx_webhooks_woocommerce', '0004_woocommerceorder_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='woocommerceorder',
            old_name='id',
            new_name='order_id',
        ),
        migrations.AlterField(
            model_name='woocommerceorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edx_webhooks_woocommerce.WooCommerceOrder', to_field='order_id'),
        ),
        # Temporary modification to ensure the new ID field is added
        migrations.AddField(
            model_name='woocommerceorder',
            name='id',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='woocommerceorder',
            name='order_id',
            field=models.BigIntegerField(editable=False),
        ),
        # Populate the auto incremented ID field from the first record
        migrations.RunPython(populate),
        # Remove default value from the primary key
        migrations.AddField(
            model_name='woocommerceorder',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='woocommerceorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edx_webhooks_woocommerce.WooCommerceOrder'),
        ),
    ]
