# Generated by Django 2.2.20 on 2021-04-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_webhooks_woocommerce', '0005_rename_id_to_order_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='woocommerceorder',
            constraint=models.UniqueConstraint(fields=('order_id', 'action'), name='unique_order_id_action'),
        ),
    ]
