# Generated by Django 2.2.20 on 2021-04-13 06:55

from django.db import migrations, models
import django.db.models.deletion


def populate(apps, schema_editor):
   model = apps.get_model('edx_webhooks_woocommerce', 'woocommerceorder')
   for index, item in enumerate(model.objects.all(), start=1):
       item.id = index
       item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('edx_webhooks_woocommerce', '0005_rename_id_to_order_id'),
    ]

    operations = [
        # Populate the auto incremented ID field from the first record
        migrations.RunPython(populate),
        # Remove default value from the primary key
        migrations.AddField(
            model_name='woocommerceorder',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='woocommerceorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edx_webhooks_woocommerce.WooCommerceOrder'),
        ),
        migrations.AddConstraint(
            model_name='woocommerceorder',
            constraint=models.UniqueConstraint(fields=('order_id', 'action'), name='unique_order_id_action'),
        ),
    ]
